name: Sync Summaries to Google Drive

on:
  push:
    branches:
      - main 

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Sync Files to Google Drive
        uses: Jumbo810/Upload_Github_Artifacts_TO_GDrive@v2.3.5
        with:
          credentials: ${{ secrets.GDRIVE_CREDENTIALS }}
          parent_folder_id: '1Zg9OW29nYIG-n_slTTCv0OHK1VhDCB7y'
          target: '**/*.md' 
          override: false
